name: "Electric Mavericks"
title: "indie rock trio for hire"
description:
  - "Electric Mavericks are dynamic indie rock trio for hire based in"
  - ". The perfect addition to parties, weddings, and festivals."
baseurl: ""
url: "https://electricmavericks.co.uk"
email: "info@electricmavericks.co.uk"

meta_image: "electricmavericks.webp"
hero_video_id: "eagdJADNbDc"
staticforms_key: "e20faf4c-267c-47fe-b62f-f9a52dfbd7c8"
google_tag_id: "G-M2561NPM9B"
recaptcha_sitekey: "6LeqsaMoAAAAAEeh6T7GRGh-M7663g3mM6wLpzpj"

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
      title: "Electric Mavericks"
      location: "Wiltshire and Berkshire"

plugins:
  - jekyll-sitemap

sass:
  style: compressed

exclude:
  - docker-compose.yml
