const repertoire = [
  "ABBA - Does Your Mother Know",
  "AC/DC - Highway to Hell",
  "Adele - Rolling In The Deep",
  "Alice In Chains - Man In The Box",
  "Amy Winehouse - Valerie",
  "Arctic Monkeys - I Bet You Look Good on the Dancefloor",
  "Ash - Shining Light",
  "Ben E King - Stand By Me",
  "Blink-182 - All The Small Things",
  "Blink-182 - First Date",
  "Blondie - One Way Or Another",
  "Blur - Parklife",
  "Blur - Song 2",
  "Bob Marley - Three Little Birds",
  "Bon Jovi - Livin On A Prayer",
  "Bruno Mars - Treasure",
  "Bryan Adams - Run To You",
  "Bryan Adams - Summer of 69",
  "Busted - Year 3000",
  "CeeLo Green - Forget You",
  "Christina Perri - 1000 Years",
  "Chuck Berry - Johnny B Goode",
  "Coldplay - Yellow",
  "Daft Punk - Get Lucky",
  "DNCE - Cake By The Ocean",
  "Ed Sheeran - Thinkin Out Loud",
  "Electric Six - Gay Bar",
  "Elvis Presley - Can't Help Falling in Love",
  "Elvis Presley - Hound Dog",
  "Elvis Presley - Jailhouse Rock",
  "Fleetwood Mac - Go Your Own Way",
  "Florence & The Machine - You've Got The Love",
  "Foo Fighters - Learn To Fly",
  "Foo Fighters - Times Like These",
  "Fountains of Wayne - Stacy's Mom",
  "Frankie Valli - Can't Take My Eyes Off You",
  "Franz Ferdinand - Take Me Out",
  "Free - Alright Now",
  "George Ezra - Blame It On Me",
  "George Ezra - Paradise",
  "George Ezra - Shotgun",
  "George Michael - Faith",
  "Green Day - Basket Case",
  "Guns N Roses - Sweet Child O Mine",
  "Harry Styles - As It Was",
  "Harry Styles - Watermelon Sugar",
  "Huey Lewis - Power Of Love",
  "Jack Johnson - Better Together",
  "James Brown - I Feel Good",
  "Jeff Beck - Hi Ho Silver Lining",
  "Jet - Are You Gonna Be My Girl",
  "Jimmy Eat World - The Middle",
  "Joan Jett - I Love Rock N Roll",
  "Justin Timberlake - Can't Stop The Feeling",
  "Kaiser Chiefs - I Predict A Riot",
  "Katrina and The Waves - Walking On Sunshine",
  "Kenny Loggins - Footloose",
  "Kings of Leon - Sex On Fire",
  "Kings of Leon - Use Somebody",
  "Lenny Kravitz - Are You Gonna Go My Way",
  "Lionel Richie - Dancing on the Ceiling",
  "Lumineers - Ho Hey",
  "Luther Vandross - Never Too Much",
  "Lynyrd Skynyrd - Sweet Home Alabama",
  "Mark Ronson - Uptown Funk",
  "Mcfly - Five Colours",
  "Men At Work - Land Down Under",
  "Neil Diamond - Sweet Caroline",
  "Nirvana - Smells Like Teen Spirit",
  "Oasis - Cigarettes & Alcohol",
  "Oasis - Don't Look Back",
  "Oasis - She's Electric",
  "Oasis - Slide Away",
  "Oasis - Wonderwall",
  "One Republic - Counting Stars",
  "Pharrell Williams - Happy",
  "Prince - Kiss",
  "Prince - Purple Rain",
  "PULP - Common People",
  "PULP - Disco 2000",
  "Queen - Crazy Little thing",
  "Robbie Williams - Angels",
  "Robbie Williams - Let Me Entertain You",
  "Robert Palmer - Addicted To Love",
  "Rollin Stones - Jumpin Jack Flash",
  "Sam & Dave - Soul Man",
  "Smash Mouth - All Star",
  "Soft Cell - Tainted Love",
  "Stealers Wheel - Stuck In the Middle",
  "Stereophonics - Dakota",
  "Stevie Wonder - Signed Sealed Delivered",
  "Stevie Wonder - Superstition",
  "The Beatles - Day Tripper",
  "The Beatles - I Saw Her Standing There",
  "The Beatles - Twist and Shout",
  "The Buzzcocks - Ever Fallen In Love",
  "The Chainsmokers - Something Just Like This",
  "The Clash - Should I Stay Or Should I Go",
  "The Cranberries - Zombie",
  "The Darkness - I Believe In A Thing Called Love",
  "The Doobie Brothers - Long Train Running",
  "The Fratellis - Chelsea Dagger",
  "The Jam - Town Called Malice",
  "The Killers - Mr Brightside",
  "The Kinks - All Day and All of the Night",
  "The Kinks - You Really Got Me",
  "The Knack - My Sharona",
  "The Kooks - Naive",
  "The Monkees - I'm A Believer",
  "The Proclaimers - 500 miles",
  "The Rembrants - I'll Be There For You",
  "The Strokes - Last Nite",
  "The Weeknd - Blinding Lights",
  "Tina Turner - Proud Mary",
  "Tracy Chapman - Fast Car",
  "Van Morrison - Brown Eyed Girl",
  "Walk the Moon - Shut Up and Dance",
  "Wheatus - Teenage Dirtbag",
  "Wild Cherry - Play That Funky Music",
];
